name: unn_grading
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  dio: ^5.2.1+1
  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6

  # desktop_drop: ^0.5.0
  super_drag_and_drop: ^0.8.24
  dropdown_button2: ^2.3.9
  file_picker: ^8.1.2
  menu_bar: ^0.5.3
  mime: ^2.0.0
  pluto_grid: ^8.0.0
  url_launcher: ^6.3.1

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

  # path_provider: ^2.1.4
  # pluto_grid_export: ^1.0.6
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/