name: unn_grading
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dio: ^5.2.1+1
  dio_refresh: ^1.0.3

  either_dart: ^1.0.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  bloc_concurrency:

  jiffy: ^6.3.2
  dropdown_button2: ^2.3.9
  super_drag_and_drop: ^0.8.24

  file_picker: ^8.1.2
  path_provider: ^2.1.4
  mime: ^2.0.0

  menu_bar: ^0.5.3
  pluto_grid: ^8.0.0

  url_launcher: ^6.3.1

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/